tap "achannarasappa/tap"
tap "cloudflare/cloudflare"
tap "cockroachdb/tap"
tap "daggy1234/tap"
tap "getsentry/tools"
tap "gromgit/fuse"
tap "hashicorp/tap"
tap "khanhas/tap"
tap "orf/brew"
tap "randomplum/gtkwave"
tap "riscv/riscv"
tap "romkatv/powerlevel10k"
tap "rs/tap"
tap "stripe/stripe-cli"
tap "vovkos/ioninja"
# TIFF library and utilities
brew "libtiff"
# Image format providing lossless and lossy compression for web images
brew "webp"
# New file format for still image compression
brew "jpeg-xl"
# Core application library for C
brew "glib"
# Improved shell history for zsh, bash, fish and nushell
brew "atuin"
# Bourne-Again SHell, a UNIX command interpreter
brew "bash"
# Open-source, cross-platform JavaScript runtime environment
brew "node"
# Secure and free password manager for all of your devices
brew "bitwarden-cli"
# New way to see and navigate directory trees
brew "broot"
# Glorious Glasgow Haskell Compilation System
brew "ghc"
# Command-line interface for Cabal and Hackage
brew "cabal-install"
# Vector graphics library with cross-device output support
brew "cairo"
# C parser in Python
brew "pycparser"
# C Foreign Function Interface for Python
brew "cffi"
# Cloudflare Tunnel client (formerly Argo Tunnel)
brew "cloudflared"
# Cross-platform make
brew "cmake"
# Dependency manager for Cocoa projects
brew "cocoapods"
# GNU File, Shell, and Text utilities
brew "coreutils"
# C library implementing the SSH2 protocol
brew "libssh2"
# Get a file from an HTTP, HTTPS or FTP server
brew "curl"
# Secure runtime for JavaScript and TypeScript
brew "deno"
# Interpreted, interactive, object-oriented programming language
brew "python@3.13"
# Text processing system for reStructuredText
brew "docutils"
# Command-line DNS client
brew "dog"
# Disk Usage/Free Utility - a better 'df' alternative
brew "duf"
# More intuitive version of du in rust
brew "dust"
# Programming language for highly scalable real-time systems
brew "erlang"
# Functional metaprogramming aware language built on Erlang VM
brew "elixir"
# Text to speech, software speech synthesizer
brew "espeak"
# C library of Git core methods that is re-entrant and linkable
brew "libgit2"
# Modern, maintained replacement for ls
brew "eza"
# Test various flash cards
brew "f3"
# Easiest way to build and release mobile apps
brew "fastlane"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Library to load and enumerate PKCS#11 modules
brew "p11-kit"
# Validating, recursive, caching DNS resolver
brew "unbound"
# GNU Transport Layer Security (TLS) Library
brew "gnutls"
# OpenType text shaping engine
brew "harfbuzz"
# Image processing and image analysis library
brew "leptonica"
# Subtitle renderer for the ASS/SSA subtitle format
brew "libass"
# NaCl networking and cryptography library
brew "libsodium"
# Framework for layout and rendering of i18n text
brew "pango"
# Secure Reliable Transport
brew "srt"
# OCR (Optical Character Recognition) engine
brew "tesseract"
# High-performance, asynchronous messaging library
brew "zeromq"
# Play, record, convert, and stream select audio and video codecs
brew "ffmpeg"
# Play, record, convert, and stream audio and video
brew "ffmpeg@4"
# Command-line fuzzy finder written in Go
brew "fzf"
# Interact with Google Gemini AI models from the command-line
brew "gemini-cli"
# GitHub command-line tool
brew "gh"
# Interpreter for PostScript and PDF
brew "ghostscript"
# Distributed revision control system
brew "git"
# Prolog compiler with constraint solving
brew "gnu-prolog"
# GNU implementation of the famous stream editor
brew "gnu-sed"
# Passphrase entry dialog utilizing the Assuan protocol
brew "pinentry"
# GNU Privacy Guard (OpenPGP)
brew "gnupg"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Package compiler and linker metadata toolkit
brew "pkgconf"
# Generate introspection data for GObject libraries
brew "gobject-introspection"
# Ping, but with a graph
brew "gping"
# GNU Ubiquitous Intelligent Language for Extensions
brew "guile"
# Cross-platform program for developing Haskell projects
brew "haskell-stack"
# Improved top (interactive process viewer)
brew "htop"
# Configurable static site generator
brew "hugo"
# Command-line benchmarking tool
brew "hyperfine"
# Verilog simulation and synthesis tool
brew "icarus-verilog"
# ISO/IEC 23008-12:2017 HEIF file format decoder and encoder
brew "libheif"
# Interpreted, interactive, object-oriented programming language
brew "python@3.12", link: false
# Tools and libraries to manipulate images in select formats
brew "imagemagick"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Implementation of the file(1) command
brew "libmagic"
# Postgres C API library
brew "libpq"
# Library to render SVG files using Cairo
brew "librsvg"
# C library for reading, creating, and modifying zip archives
brew "libzip"
# Rainbows and unicorns in your console!
brew "lolcat"
# Bare libuv bindings for lua
brew "luv"
# Swiss Army Knife for macOS
brew "m-cli"
# Java-based project management
brew "maven"
# Video processing framework with simplicity in mind
brew "vapoursynth"
# Feature-rich command-line audio/video downloader
brew "yt-dlp"
# Media player based on MPlayer and mplayer2
brew "mpv"
# NCurses Disk Usage
brew "ncdu"
# Fast, highly customisable system info script
brew "neofetch"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# HTTP/2 C Library
brew "nghttp2"
# Command-line Git information tool
brew "onefetch"
# On-chip debugging, in-system programming and boundary-scan testing
brew "open-ocd"
# Swiss-army knife of markup format conversion
brew "pandoc"
# Perl compatible regular expressions library
brew "pcre"
# Highly capable, feature-rich programming language
brew "perl"
# Pinentry for GPG on Mac
brew "pinentry-mac"
# Execute binaries from Python packages in isolated environments
brew "pipx"
# Fast, disk space efficient package manager
brew "pnpm"
# Interpreted, interactive, object-oriented programming language
brew "python@3.10"
# Cowsay but with ponies
brew "ponysay"
# PDF rendering library (based on the xpdf-3.0 code base)
brew "poppler"
# Object-relational database system
brew "postgresql@14"
# Theme for zsh
brew "powerlevel10k"
# Modern replacement for ps written in Rust
brew "procs"
# Protocol buffers (Google's data interchange format)
brew "protobuf"
# Interpreted, interactive, object-oriented programming language
brew "python@3.11"
# Interpreted, interactive, object-oriented programming language
brew "python@3.9"
# Generic machine emulator and virtualizer
brew "qemu"
# Install various Ruby versions and implementations
brew "ruby-build"
# Ruby version manager
brew "rbenv"
# Rsync for cloud storage
brew "rclone"
# Persistent key-value database, with built-in net interface
brew "redis"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Rust toolchain installer
brew "rustup"
# Fast and accurate code counter with complexity and COCOMO estimates
brew "scc"
# Prints a steam locomotive if you type sl instead of ls
brew "sl"
# Command-line interface for https://speedtest.net bandwidth tests
brew "speedtest-cli"
# MIPS32 simulator
brew "spim"
# Statistics from the command-line
brew "st"
# Organize software neatly under a single directory tree (e.g. /usr/local)
brew "stow"
# Modern and pretty fancy file manager for the terminal
brew "superfile"
# ISO/Edinburgh-style Prolog interpreter
brew "swi-prolog"
# Simplified and community-driven man pages
brew "tldr"
# Program that allows you to count code, quickly
brew "tokei"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Extremely fast Python package installer and resolver, written in Rust
brew "uv"
# Tool for creating isolated virtual python environments
brew "virtualenv"
# Internet file retriever
brew "wget"
# JavaScript package manager
brew "yarn"
# Modular BSD reimplementation of NASM
brew "yasm"
# Download Youtube Video in Golang
brew "youtubedr"
# UNIX shell (command interpreter)
brew "zsh"
# Terminal stock ticker with live updates and position tracking
brew "achannarasappa/tap/ticker"
# CockroachDB Cloud CLI
brew "cockroachdb/tap/ccloud"
# Distributed SQL database
brew "cockroachdb/tap/cockroach"
# A cli for Managing https://dagpi.xyz
brew "daggy1234/tap/dagpi"
# The Sentry Wizard helps you set up your projects with Sentry
brew "getsentry/tools/sentry-wizard"
# GTKWave
brew "randomplum/gtkwave/gtkwave", args: ["HEAD"]
# RISC-V toolchain including gcc (with newlib), simulator (spike), and pk
brew "riscv/riscv/riscv-tools"
# The power of curl, the ease of use of httpie.
brew "rs/tap/curlie"
# Stripe CLI utility
brew "stripe/stripe-cli/stripe"
# Command-line interface for 1Password
cask "1password-cli"
# Memory training application
cask "anki"
# Compact TeX distribution as alternative to the full TeX Live / MacTeX
cask "basictex"
# E-books management software
cask "calibre"
# Terminal-based AI coding assistant
cask "claude-code"
# UI toolkit for building applications for mobile, web and desktop
cask "flutter"
cask "font-hack-nerd-font"
cask "font-jetbrains-mono"
# Development environment
cask "hashicorp/tap/hashicorp-vagrant"
# System monitor for the status bar
cask "iglance"
# Digital logic designer and simulator
cask "logisim-evolution"
# File system integration
cask "macfuse"
# Reverse proxy, secure introspectable tunnels to localhost
cask "ngrok"
# Replacement for Docker Desktop
cask "orbstack"
# Simulator that runs MIPS32 assembly language programmes
cask "qtspim"
# Compiler for the Standard ML '97 programming language
cask "smlnj"
vscode "1password.op-vscode"
vscode "1yib.rust-bundle"
vscode "adpyke.vscode-sql-formatter"
vscode "akamud.vscode-theme-onedark"
vscode "alefragnani.project-manager"
vscode "alexcvzz.vscode-sqlite"
vscode "amazonwebservices.aws-toolkit-vscode"
vscode "anthropic.claude-code"
vscode "batisteo.vscode-django"
vscode "bierner.markdown-footnotes"
vscode "bradlc.vscode-tailwindcss"
vscode "castwide.solargraph"
vscode "christian-kohler.npm-intellisense"
vscode "christian-kohler.path-intellisense"
vscode "chrmarti.regex"
vscode "codezombiech.gitignore"
vscode "coolbear.systemd-unit-file"
vscode "dart-code.dart-code"
vscode "davidanson.vscode-markdownlint"
vscode "dbaeumer.vscode-eslint"
vscode "docker.docker"
vscode "donjayamanne.git-extension-pack"
vscode "donjayamanne.githistory"
vscode "donjayamanne.python-environment-manager"
vscode "donjayamanne.python-extension-pack"
vscode "dsznajder.es7-react-js-snippets"
vscode "dukecs201.duke-cs201-java-extension-pack"
vscode "dustypomerleau.rust-syntax"
vscode "eamodio.gitlens"
vscode "ecmel.vscode-html-css"
vscode "editorconfig.editorconfig"
vscode "equimper.react-native-react-redux"
vscode "ericadamski.carbon-now-sh"
vscode "esbenp.prettier-vscode"
vscode "felipecaputo.git-project-manager"
vscode "firefox-devtools.vscode-firefox-debug"
vscode "flowtype.flow-for-vscode"
vscode "formulahendry.auto-close-tag"
vscode "formulahendry.auto-complete-tag"
vscode "formulahendry.auto-rename-tag"
vscode "framer.framer-syntax"
vscode "github.codespaces"
vscode "github.github-vscode-theme"
vscode "github.remotehub"
vscode "github.vscode-github-actions"
vscode "golang.go"
vscode "google.gemini-cli-vscode-ide-companion"
vscode "grapecity.gc-excelviewer"
vscode "haskell.haskell"
vscode "hoovercj.haskell-linter"
vscode "humao.rest-client"
vscode "icrawl.discord-vscode"
vscode "iocave.customize-ui"
vscode "iocave.monkey-patch"
vscode "jakebecker.elixir-ls"
vscode "james-yu.latex-workshop"
vscode "janisdd.vscode-edit-csv"
vscode "jcanero.hoogle-vscode"
vscode "joebayer1340.wildberry-theme"
vscode "joeyyizhao.mongo-runner"
vscode "johnpapa.vscode-peacock"
vscode "juanblanco.solidity"
vscode "justusadam.language-haskell"
vscode "k--kato.intellij-idea-keybindings"
vscode "kevinrose.vsc-python-indent"
vscode "khaeransori.json2csv"
vscode "ldez.ignore-files"
vscode "lextudio.restructuredtext"
vscode "llvm-vs-code-extensions.lldb-dap"
vscode "mads-hartmann.bash-ide-vscode"
vscode "mathematic.vscode-latex"
vscode "maxgabriel.brittany"
vscode "maziac.asm-code-lens"
vscode "mechatroner.rainbow-csv"
vscode "mgesbert.python-path"
vscode "mhutchie.git-graph"
vscode "mikestead.dotenv"
vscode "mkloubert.vscode-http-client"
vscode "mongodb.mongodb-vscode"
vscode "mrpbennett.atlantic-night"
vscode "ms-azuretools.vscode-containers"
vscode "ms-azuretools.vscode-docker"
vscode "ms-python.autopep8"
vscode "ms-python.debugpy"
vscode "ms-python.isort"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-python.vscode-python-envs"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode-remote.remote-wsl"
vscode "ms-vscode.azure-repos"
vscode "ms-vscode.cmake-tools"
vscode "ms-vscode.cpp-devtools"
vscode "ms-vscode.cpptools"
vscode "ms-vscode.cpptools-extension-pack"
vscode "ms-vscode.cpptools-themes"
vscode "ms-vscode.makefile-tools"
vscode "ms-vscode.remote-explorer"
vscode "ms-vscode.remote-repositories"
vscode "ms-vscode.remote-server"
vscode "ms-vscode.vscode-serial-monitor"
vscode "ms-vscode.vscode-typescript-next"
vscode "mshr-h.veriloghdl"
vscode "msjsdiag.vscode-react-native"
vscode "mtxr.sqltools"
vscode "mtxr.sqltools-driver-pg"
vscode "naumovs.color-highlight"
vscode "negokaz.live-server-preview"
vscode "nixon.env-cmd-file-syntax"
vscode "njpwerner.autodocstring"
vscode "nwallace.peep"
vscode "octref.vetur"
vscode "oderwat.indent-rainbow"
vscode "pkief.material-icon-theme"
vscode "plex.vscode-protolint"
vscode "pnp.polacode"
vscode "prisma.prisma"
vscode "rajkundu.junit-jar-downloader"
vscode "rebornix.ruby"
vscode "redhat.java"
vscode "redhat.vscode-xml"
vscode "redhat.vscode-yaml"
vscode "remixproject.ethereum-remix"
vscode "rust-lang.rust-analyzer"
vscode "rvest.vs-code-prettier-eslint"
vscode "sankethdev.vscode-proto"
vscode "saratravi.elixir-formatter"
vscode "serayuzgur.crates"
vscode "sirtori.indenticator"
vscode "smockle.xcode-default-theme"
vscode "sonarsource.sonarlint-vscode"
vscode "sswg.swift-lang"
vscode "swiftlang.swift-vscode"
vscode "tamasfe.even-better-toml"
vscode "teabyii.ayu"
vscode "tomoki1207.pdf"
vscode "twxs.cmake"
vscode "vadimcn.vscode-lldb"
vscode "vasilescur.better-mips"
vscode "vincaslt.highlight-matching-tag"
vscode "visualstudioexptteam.intellicode-api-usage-examples"
vscode "visualstudioexptteam.vscodeintellicode"
vscode "vivaxy.vscode-conventional-commits"
vscode "vknabel.vscode-apple-swift-format"
vscode "vrjuliao.sml-environment"
vscode "vsciot-vscode.vscode-arduino"
vscode "vscjava.migrate-java-to-azure"
vscode "vscjava.vscode-gradle"
vscode "vscjava.vscode-java-debug"
vscode "vscjava.vscode-java-dependency"
vscode "vscjava.vscode-java-pack"
vscode "vscjava.vscode-java-test"
vscode "vscjava.vscode-java-upgrade"
vscode "vscjava.vscode-maven"
vscode "vscode-icons-team.vscode-icons"
vscode "vscodevim.vim"
vscode "vue.volar"
vscode "waderyan.gitblame"
vscode "wakatime.vscode-wakatime"
vscode "wayou.vscode-todo-highlight"
vscode "wholroyd.jinja"
vscode "wingrunr21.vscode-ruby"
vscode "yoavbls.pretty-ts-errors"
vscode "yzhang.markdown-all-in-one"
vscode "zamerick.vscode-caddyfile-syntax"
vscode "ziyasal.vscode-open-in-github"
vscode "zxh404.vscode-proto3"
go "github.com/akshaybabloo/dnode"
go "golang.org/x/tools/gopls"
go "honnef.co/go/tools/cmd/staticcheck"
go "golang.org/x/website/tour"
cargo "cargo-bundle"
cargo "cargo-packager"
cargo "cargo-sweep"
cargo "exa"
